## Puerto de la aplicación
server:
  port: 8092

## Postgres
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://containers-us-west-43.railway.app:6438/railway
    username: postgres
    password: VIv17qdHMv21damSYtjC
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
    
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
        
        
